Consider the Iris data, use two mulilayer perceptrons, namely, neural networks with one and and two hidden layers, respectively. Here consider PyTorch implementation.

In [81]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [82]:
class Net1(nn.Module):
    def __init__(self):
        super(Net1, self).__init__()
        self.hidden1 = nn.Linear(4, 5)
        self.output = nn.Linear(5, 3)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = self.hidden1(x)
        x = F.relu(x)
        x = self.output(x)
        x = self.softmax(x)

        return x

In [83]:
class Net2(nn.Module):
    def __init__(self):
        super(Net2, self).__init__()
        self.hidden1 = nn.Linear(4, 5)
        self.hidden2 = nn.Linear(5, 10)
        self.output = nn.Linear(10, 3)
        self.softmax = nn.Softmax(dim=1)
    def forward(self, x):
        x = self.hidden1(x)
        x = F.relu(x)
        x = self.hidden2(x)
        x = F.relu(x)
        x = self.output(x)
        x = self.softmax(x)

        return x

In [84]:
def fit(model, epochs, x, y, iter_report=0):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
    for epoch in range(epochs):
        optimizer.zero_grad()
        y_pred = model(x)
        loss = criterion(y_pred, y)
        loss.backward()
        optimizer.step()

        if iter_report != 0 and epoch % iter_report == 0:
            print(epoch, loss.item())
    return model

In [85]:
iris = datasets.load_iris()
X = iris.data[:, :]
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1, stratify=y)

In [86]:
net1 = Net1()
net1

Net1(
  (hidden1): Linear(in_features=4, out_features=5, bias=True)
  (output): Linear(in_features=5, out_features=3, bias=True)
  (softmax): Softmax(dim=1)
)

In [87]:
net2 = Net2()
net2

Net2(
  (hidden1): Linear(in_features=4, out_features=5, bias=True)
  (hidden2): Linear(in_features=5, out_features=10, bias=True)
  (output): Linear(in_features=10, out_features=3, bias=True)
  (softmax): Softmax(dim=1)
)

In [88]:
X_train = torch.autograd.Variable(torch.Tensor(X_train).float())
X_test = torch.autograd.Variable(torch.Tensor(X_test).float())
y_train = torch.autograd.Variable(torch.Tensor(y_train).long())
y_test = torch.autograd.Variable(torch.Tensor(y_test).long())

In [89]:
net1 = fit(net1, 10000, X_train, y_train)

In [90]:
predict_out1 = net1(X_test)
predict_out1.data[[x for x in range(5)]]


tensor([[3.2738e-06, 1.6070e-01, 8.3929e-01],
        [3.3316e-07, 8.9565e-02, 9.1043e-01],
        [9.1013e-01, 8.7224e-02, 2.6455e-03],
        [5.4201e-07, 1.0172e-01, 8.9828e-01],
        [9.1013e-01, 8.7224e-02, 2.6455e-03]])

In [64]:
_, predict_y1 = torch.max(predict_out1, 1)
predict_y1.data

tensor([2, 2, 0, 2, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 2, 0, 1, 2, 0, 1, 2, 1, 1, 1,
        2, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0,
        0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2, 1, 1, 2, 1, 2, 0, 1, 0,
        0, 1, 0])

In [56]:
print("Accuracy:", accuracy_score(y_test.data, predict_y1.data))

Accuracy: 0.9733333333333334


In [57]:
net2 = fit(net2, 10000,  X_train, y_train)

In [79]:
predict_out2 = net2(X_test)
predict_out2.data[[x for x in range(5)]]


tensor([[9.0799e-12, 2.4720e-02, 9.7528e-01],
        [5.5127e-14, 4.0082e-03, 9.9599e-01],
        [9.8344e-01, 1.6563e-02, 2.1241e-06],
        [1.1823e-13, 5.2672e-03, 9.9473e-01],
        [9.8344e-01, 1.6563e-02, 2.1241e-06]])

In [59]:
_, predict_y2 = torch.max(predict_out2, 1)
predict_y2

tensor([2, 2, 0, 2, 0, 1, 1, 1, 2, 1, 0, 2, 2, 2, 2, 0, 1, 2, 0, 1, 2, 1, 1, 1,
        2, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0,
        0, 1, 2, 0, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 0, 2, 1, 1, 2, 1, 2, 0, 1, 0,
        0, 1, 0])

In [60]:
print("Accuracy:", accuracy_score(y_test.data, predict_y2.data))

Accuracy: 0.9866666666666667
